remove custom functions for bitwarden cli

diff --git a/dot_bashrc b/dot_bashrc
--- a/dot_bashrc
+++ b/dot_bashrc
@@ -108,10 +108,26 @@ fi
 # Enable Vi keybinds
 set -o vi
 
-# Load custom functions
-if [ -f ~/.bash_functions ]; then
-  . ~/.bash_functions
-fi
+# Some custom functions
+dotfiles() {
+  if ! command -v chezmoi >/dev/null 2>&1; then
+    echo "missing chezmoi" >&2
+  fi
+
+  if [[ -f "$1" ]]; then
+    chezmoi edit -a --watch "$1"
+  else
+    local file
+    file=$(chezmoi managed -i files | fzf -q "$1")
+    [[ -n "$file" ]] && chezmoi edit -a --watch "$HOME/$file"
+  fi
+}
+
+sshrm() {
+  local selected
+  selected=$(cut -d ' ' -f1 ~/.ssh/known_hosts | uniq | fzf-tmux -p -- -q "$1")
+  [[ -n "$selected" ]] && ssh-keygen -R "$selected"
+}
 
 # Local, machine-only config (never managed by chezmoi)
 if [ -f ~/.bashrc.local ]; then
